dist: bionic
sudo: false
language: cpp

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - librocksdb-dev

script:
  - CORES=$(grep -c ^processor /proc/cpuinfo)
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 make -j $CORES -l $CORES

# safelist
branches:
  only:
    - master
